name: Backpack
version: '1.0.0'
main: com.backpack.Backpack
api-version: '1.21'
author: YourName
description: A backpack plugin for Minecraft
commands:
  backpack:
    description: Open your backpack
    usage: /backpack
    aliases: [bp]
permissions:
  backpack.use:
    description: Allows players to use backpacks
    default: true
  backpack.admin:
    description: Admin permissions for backpack
    default: op
